---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: heliocentric-model-no-pluto-app
  namespace: argocd
spec:
  destination:
    namespace: heliocentric-no-pluto
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./declarative/manifests/heliocentric-model-no-pluto
    repoURL: https://github.com/zavarka/gitops-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true